<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
    <OutputType>Library</OutputType>
    <Configurations>Debug;Release;DebugWin;ReleaseWin</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>DEBUG;</DefineConstants>
    <Externalconsole>True</Externalconsole>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Externalconsole>True</Externalconsole>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Posix" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sharpen\Sharpen.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Openur.Mono.Unix" Version="7.1.0.256" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>
</Project>